### ISSUE TITLE
What is the status with current ejabberd?

### ISSUE THREAD

**Issue by Neustradamus** [cburschka/ejabberd-auth-php#22]
What is the status with current ejabberd?

**Comment by MartinInFrankfurtAM** [comment]
Schön von Dir zu lesen, was Dich bewgt, mlSC.

Neustradamus <notifications@github.com> schrieb am Mo., 22. Juni 2020,
06:42:

**Comment by cburschka** [comment]
This project is not maintained. I don't know if it still works with more recent versions of ejabberd, unfortunately.

(Please excuse the spam comment.)
